version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"   # Expose for local tools!
    volumes:
      - expense-manager:/data/db

  
volumes:
  expense-manager:
